#
# Site settings
#
remote_theme: thinh-vu/pretty-docs
url: https://thinh-vu.github.io
baseurl: /vnstock-docs
title: &site_title vnstock Docs
description: &site_description Tài liệu hướng dẫn sử dụng vnstock trong phân tích thị trường chứng khoán Việt Nam
branding:
  icon:
    name: icon_documents_alt
  highlight: vnstock
  bold: Docs
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: Thịnh Vũ
  facebook: &site_owner_twitter mr.thinh.ueh
  linkedin: &site_owner_twitter thinh-vu
  twitter: &site_owner_twitter mrthinh360
  copyright:
    # notice: Lorem Ipsum
    author: "[Vnstock.site | Thinh Vu Blog](https://thinhvu.com/)"


#
# Social
#
open_graph:
  title: *site_title
  site_name: *site_title
  description: *site_description
  locale: en_US
  image: /assets/images/thumb.png
# twitter_cards:
#   title: *site_title
#   description: *site_description
#   creator: *site_owner_twitter
#   card: summary_large_image
#   image: /assets/images/thumb.png
# share:
#   facebook:
#     class: fb-like
#     action: like
#     layout: button_count
#     show-faces: false
#     share: false
#   twitter:
#     via: *site_owner_twitter
#     text: &site_description
#     title: Tweet
  # github:
  #   repo: thinh-vu/vnstock
  #   position: right
  #   color: red


# Google Analytics
google_analytics: G-5RWXJ4J4N7


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
