site_name: Vnstock Docs
site_url: https://docs.vnstock.site
site_description: >-
  Vnstock Docs
theme:
  custom_dir: docs/material/overrides
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/vnstock_logo_bw.png
  favicon: assets/images/vnstock_logo_bw.png
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    - scheme: default
      primary: vnstock
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for light mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - toc.integrate # tắt để hiện riêng bên thanh bên phải
    - navigation.top
    - announce.dismiss # tắt banner thông báo bởi user
  # language: en
extra_css:
  - stylesheets/extra.css
edit_uri: edit/main/docs/docs                 
plugins:
  - info
  - glightbox
  # - search
  - tags:
      enabled: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social: # display a preview on social for links
      cards_layout: default/invert
      cards_layout_options:
        background_color: "#279B48" 
  # - meta # blog metadata
  - blog:
      enabled: true
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 2
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_excerpt: optional
      post_excerpt_max_categories: 2
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 300
      categories: true
      categories_name: Danh mục
      categories_url_format: "category/{slug}"
      categories_toc: true
      archive: true
      archive_name: Dòng thời gian
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      archive_toc: true
      # categories_allowed:
      #   - hướng dẫn
      #   - kiến thức
      #   - How to
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 


markdown_extensions:
  - toc:
      permalink: true
      title: Mục lục
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # button
  - attr_list
  # annotations
  - md_in_html
  - pymdownx.superfences
  # footnotes
  - footnotes
  # markdown formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # database
  - tables
  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # image
  - attr_list
  - md_in_html
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    # provider: google
    # property: G-DJT4KFYTW8
    provider: custom
    property: Google Tag Manager
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/thinh-vu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/vnstock
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/vnstock.official/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ruugCSWVCJ
  generator: false
  # version:
  #   provider: mike
  #   default: stable
  # alternate:
  # - name: English
  #   link: /en/ 
  #   lang: en
  # - name: Việt Nam
  #   link: /vi/
  #   lang: vi
repo_name: vnstock
repo_url: https://github.com/thinh-vu/vnstock
copyright: Copyright &copy; 2023 | vnstock.site

# Page tree
nav:
  - Trang chủ: index.md
  - Hướng dẫn nhanh: 
    - Bắt đầu: start/huong-dan-su-dung-nhanh-vnstock.md
    - Chọn phiên bản: start/huong-dan-cai-dat-vnstock-python.md
    - Tài nguyên website: start/tai-nguyen-quan-trong-vnstock-website.md
    # - Danh mục thẻ nội dung: tags.md
  - Tính năng:
    - Danh sách niêm yết: functions/listing.md
    - Thông tin cơ bản: functions/fundamental.md
    - Giá cổ phiếu: functions/technical.md 
    - Báo cáo tài chính: functions/financial.md
    - Chỉ số tài chính: functions/ratio.md
    - Bộ lọc cổ phiếu: functions/screener.md
    - So sánh cổ phiếu: functions/comparison.md
    - Xếp hạng cổ phiếu: functions/rating.md
    - Định giá cổ phiếu: functions/evaluation.md
    - Thông tin quỹ mở: functions/funds.md
    - Thị trường: functions/market.md
    - Xuất dữ liệu: functions/export.md
    - Biểu diễn dữ liệu: functions/chart.md
  - Ứng dụng & Tích hợp: 
    - Web app: integrate/web_app.md
    - Biểu diễn dữ liệu: integrate/vnstock_ezchart.md
    - FMP - Dữ liệu tài chính thế giới: integrate/financialmodelingprep-vnstock.md
    - Google Sheets: integrate/google_sheets.md
    - Amibroker: integrate/amibroker.md
    - Streamlit: integrate/streamlit.md
    - Huggingface: integrate/huggingface.md
    - OpenBB Terminal: integrate/OpenBBTerminal.md
    - TA-Lib: integrate/ta_lib.md
    - Thư viện Backtesting: integrate/backtesting.md
    - SSI Fast Connect API: integrate/ssi_fast_connect_api.md
    - DNSE Lightspeed API: integrate/dnse_api.md
    - PyTesseract OCR: integrate/pytesseract-ocr-chuyen-doi-tai-lieu-tai-chinh-scan-sang-van-ban.md
    - Gửi tin nhắn Telegram/Slack: integrate/telegram-slack-gui-tin-nhan-thong-bao-qua-chat-tu-python.md
  - Insiders Program: insiders-program/gioi-thieu-chuong-trinh-vnstock-insiders-program.md
  - Cộng đồng: 
    - Tham gia cộng đồng: community/join.md
    - Tài trợ dự án: community/tai-tro-du-an-vnstock.md
    # - vnstock Roadmap: community/vnstock-road-map-lo-trinh-phat-trien-vnstock.md
    - Thành viên tích cực: community/vnstock-contributors-thanh-vien-tich-cuc.md
    - Lan tỏa vnstock: community/lan-toa-trai-nghiem-voi-vnstock.md
    - Góp ý & phản hồi: community/feedback.md
    - Đóng góp mã nguồn: community/contribute.md
  - FAQs: 
    - Giấy phép: trich-dan-va-giay-phep-su-dung-vnstock.md
    - Miễn trừ trách nhiệm: disclaimer.md
    - Sản phẩm: faq/feature.md
    - Cộng đồng: faq/community.md
    - Ủng hộ dự án: faq/ung-ho-du-an-vnstock.md
    - Hỗ trợ người dùng: faq/vnstock-ho-tro-nguoi-dung.md
  - Phiên bản: changes_log.md
  - Khóa học Python: course.md
  - Kiến thức: blog/index.md
  # - Từ điển kinh tế: docs/financial-dictionary/index.md



