site_name: Vnstokc Docs
site_url: https://docs.vnstock.site
site_description: >-
  Vnstock Docs
theme:
  custom_dir: docs/material/overrides
  name: material
  icon:
    repo: fontawesome/brands/github
  # logo: assets/vnstock_logo_bw.png
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for light mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - toc.integrate # tắt để hiện riêng bên thanh bên phải
    - navigation.top
  # language: en
extra_css:
  - stylesheets/extra.css
edit_uri: edit/main/docs/docs                 
plugins:
  - glightbox
  - blog
  # - search
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - toc:
      permalink: true
      title: Mục lục
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # button
  - attr_list
  # annotations
  - md_in_html
  - pymdownx.superfences
  # footnotes
  - footnotes
  # markdown formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # database
  - tables
  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # image
  - attr_list
  - md_in_html
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    # provider: google
    # property: G-DJT4KFYTW8
    provider: custom
    property: Google Tag Manager
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/thinh-vu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thinh-vu/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/mr.thinh.ueh
  # alternate:
  # - name: English
  #   link: /en/ 
  #   lang: en
  # - name: Việt Nam
  #   link: /vi/
  #   lang: vi
repo_name: vnstock
repo_url: https://github.com/thinh-vu/vnstock

# Page tree
nav:
  - Trang chủ: index.md
  - Hướng dẫn nhanh: 
    - Bắt đầu: start/start.md
    - Chọn phiên bản: start/installation.md
    - Tài nguyên: start/resources.md
  - Tính năng:
    - Danh sách niêm yết: functions/listing.md
    - Thông tin cơ bản: functions/fundamental.md
    - Giá cổ phiếu: functions/technical.md 
    - Báo cáo tài chính: functions/financial.md
    - Chỉ số tài chính: functions/ratio.md
    - Bộ lọc cổ phiếu: functions/screener.md
    - So sánh cổ phiếu: functions/comparison.md
    - Xếp hạng cổ phiếu: functions/rating.md
    - Định giá cổ phiếu: functions/evaluation.md
    - Biểu diễn dữ liệu: functions/chart.md
  - Ứng dụng: showcase.md
  - Cộng đồng: 
    - Tham gia cộng đồng: community/join.md
    - Ủng hộ quỹ: community/support.md
    - Góp sức: community/contribute.md
  - FAQs: 
    - Sản phẩm: faq/feature.md
    - Cộng đồng: faq/community.md
    - Ủng hộ dự án: faq/pricing.md
    - Hỗ trợ người dùng: faq/support.md
  - Giấy phép: cite.md
  - Phiên bản: changes_log.md
  - Miễn trừ: disclaimer.md



